//! `tests/vectors/expected.toml`: what an independent decoder must produce for every
//! vector (spec `docs/spec/CONFORMANCE.md`). The file is generated by the reference
//! reader and checked here, so it cannot drift from the vectors:
//! `cargo test -p lpk-format --test conformance -- --ignored` rewrites it and the two
//! malformed vectors.
#![allow(clippy::unwrap_used)]

mod common;

use common::journal::JOURNAL_VECTOR;
use common::recovery::{RECOVERY_DAMAGED, RECOVERY_VECTOR};
use common::sealed::{sealed_keyfile_bytes, sealed_password, SEALED_VECTORS};
use common::{vectors_dir, DICT_FILE, VECTORS};
use lpk_format::{Archive, Credentials, FormatError, MemoryPriors, Resources};
use std::fmt::Write as _;
use std::io::Cursor;

const TRUNCATED: &str = "malformed-truncated.lpk";
const HASHFLIP: &str = "malformed-hashflip.lpk";

fn read(name: &str) -> Vec<u8> {
    std::fs::read(vectors_dir().join(name)).unwrap()
}

fn creds_of(name: &str) -> Option<Credentials> {
    SEALED_VECTORS.contains(&name).then(|| Credentials {
        password: sealed_password(name).as_bytes().to_vec(),
        keyfile: (name == "sealed-keyfile.lpk").then(sealed_keyfile_bytes),
    })
}

fn open(bytes: Vec<u8>, name: &str, creds: Option<&Credentials>) -> Archive<Cursor<Vec<u8>>> {
    let mut a = Archive::open_with(Cursor::new(bytes), &Resources::default(), creds).unwrap();
    if name == "zstd-dict.lpk" {
        let mut store = MemoryPriors::new();
        store.insert(read(DICT_FILE));
        a.set_priors(Box::new(store));
    }
    a
}

/// `path size blake3` per entry in table order; kinds other than files are listed with
/// size 0 and the hash of nothing, so a decoder's directory entries are compared too.
fn files_of(a: &mut Archive<Cursor<Vec<u8>>>) -> Vec<String> {
    let table = a.entry_table().unwrap();
    let entries: Vec<_> = table.table().unwrap().iter().map(|e| e.unwrap()).collect();
    entries
        .iter()
        .map(|e| {
            let mut got = Vec::new();
            a.extract(e, &mut got).unwrap();
            format!("{} {} {}", e.path, got.len(), blake3::hash(&got).to_hex())
        })
        .collect()
}

fn cli(args: &[&str]) -> (i32, String, String) {
    let (mut out, mut err) = (Vec::new(), Vec::new());
    let code = lpk_format::cli::run(args.iter().copied(), &mut out, &mut err);
    (
        code,
        String::from_utf8(out).unwrap(),
        String::from_utf8(err).unwrap(),
    )
}

fn variant(e: &FormatError) -> String {
    let d = format!("{e:?}");
    d.split([' ', '{', '(']).next().unwrap().to_string()
}

/// The two malformed vectors, derived from `zstd-basic.lpk`.
fn malformed() -> (Vec<u8>, Vec<u8>) {
    let good = read("zstd-basic.lpk");
    // Truncated: the last 100 bytes are gone (inside the trailer frame and the index).
    let truncated = good[..good.len() - 100].to_vec();
    // Hash-flipped: one byte inside the first block's ChunkData payload.
    let a = open(good.clone(), "zstd-basic.lpk", None);
    let b = a.index().blocks[0];
    let mut flipped = good;
    let at = (b.frame_offset + b.frame_len / 2) as usize;
    flipped[at] ^= 0x01;
    (truncated, flipped)
}

fn render() -> String {
    let dir = vectors_dir();
    let mut s = String::from(
        "# Expected results for an independent decoder (docs/spec/CONFORMANCE.md).\n\
         # Generated by the reference reader; do not edit. `files`: path size BLAKE3-256 of the\n\
         # extracted bytes, in entry-table order. `list` and `verify` are the stdout of\n\
         # `lpk-decode list` and `lpk-decode verify` (exit code 0).\n",
    );
    let mut names: Vec<&str> = VECTORS.to_vec();
    names.extend(SEALED_VECTORS);
    names.push(JOURNAL_VECTOR);
    names.push(RECOVERY_VECTOR);
    for name in names {
        let creds = creds_of(name);
        let mut a = open(read(name), name, creds.as_ref());
        let files = files_of(&mut a);
        let mut args: Vec<String> = vec!["lpk-decode".into()];
        let prior = dir.join(DICT_FILE);
        if name == "zstd-dict.lpk" {
            args.extend(["--prior".into(), prior.to_str().unwrap().into()]);
        }
        if creds.is_some() {
            args.extend(["--password".into(), sealed_password(name).into()]);
        }
        if name == "sealed-keyfile.lpk" {
            args.extend([
                "--keyfile".into(),
                dir.join("sealed-keyfile.key").to_str().unwrap().into(),
            ]);
        }
        let run = |cmd: &str| {
            let mut v: Vec<&str> = args.iter().map(String::as_str).collect();
            v.push(cmd);
            let p = dir.join(name);
            v.push(p.to_str().unwrap());
            let (code, out, err) = cli(&v);
            assert_eq!((code, err.as_str()), (0, ""), "{name} {cmd}");
            out
        };
        writeln!(s, "\n[\"{name}\"]").unwrap();
        writeln!(s, "files = [").unwrap();
        for f in &files {
            writeln!(s, "  {f:?},").unwrap();
        }
        writeln!(s, "]").unwrap();
        writeln!(s, "list = {:?}", run("list")).unwrap();
        writeln!(s, "verify = {:?}", run("verify")).unwrap();
        if name == RECOVERY_VECTOR {
            writeln!(s, "check = {:?}", run("check")).unwrap();
        }
        if name == JOURNAL_VECTOR {
            let latest = a.generation();
            writeln!(s, "latest_generation = {latest}").unwrap();
            for g in 0..latest {
                let tmp = tempfile::NamedTempFile::new().unwrap();
                std::fs::write(tmp.path(), read(name)).unwrap();
                let mut f = std::fs::OpenOptions::new()
                    .read(true)
                    .write(true)
                    .open(tmp.path())
                    .unwrap();
                lpk_format::rollback(&mut f, g).unwrap();
                drop(f);
                let mut r = open(std::fs::read(tmp.path()).unwrap(), name, None);
                assert_eq!(r.generation(), g);
                writeln!(s, "files_at_generation_{g} = [").unwrap();
                for x in files_of(&mut r) {
                    writeln!(s, "  {x:?},").unwrap();
                }
                writeln!(s, "]").unwrap();
            }
        }
    }
    let (truncated, flipped) = malformed();
    for (name, bytes) in [(TRUNCATED, truncated), (HASHFLIP, flipped)] {
        let err = match Archive::open(Cursor::new(bytes), &Resources::default()) {
            Err(e) => e,
            Ok(mut a) => a.verify().unwrap_err(),
        };
        writeln!(s, "\n[\"{name}\"]").unwrap();
        writeln!(s, "error = {:?}", variant(&err)).unwrap();
        writeln!(s, "message = {:?}", err.to_string()).unwrap();
    }
    // The damaged recovery vector: opens, `check` reports one damaged shard, `repair`
    // restores the original bytes.
    let damaged = read(RECOVERY_DAMAGED);
    let mut a = open(damaged.clone(), RECOVERY_DAMAGED, None);
    let report = a.check_recovery().unwrap();
    let mut fixed = Cursor::new(Vec::new());
    let repaired =
        lpk_format::repair(Cursor::new(damaged), &mut fixed, &Resources::default()).unwrap();
    assert!(fixed.into_inner() == read(RECOVERY_VECTOR));
    let p = dir.join(RECOVERY_DAMAGED);
    let (code, out, err) = cli(&["lpk-decode", "check", p.to_str().unwrap()]);
    writeln!(s, "\n[\"{RECOVERY_DAMAGED}\"]").unwrap();
    writeln!(s, "recovery_frames = {}", report.frames).unwrap();
    writeln!(s, "shards_damaged = {}", report.shards_damaged).unwrap();
    writeln!(
        s,
        "shards_repaired_by_repair = {}",
        repaired.shards_repaired
    )
    .unwrap();
    writeln!(s, "repaired_copy_equals = \"{RECOVERY_VECTOR}\"").unwrap();
    writeln!(s, "check_exit = {code}").unwrap();
    writeln!(s, "check_stdout = {out:?}").unwrap();
    writeln!(s, "check_stderr = {err:?}").unwrap();
    s
}

#[test]
fn the_recovery_vectors_are_reproduced() {
    let good = common::recovery::build_recovery_vector();
    assert!(read(RECOVERY_VECTOR) == good);
    assert!(read(RECOVERY_DAMAGED) == common::recovery::damaged_from(&good));
}

#[test]
fn the_recovery_vector_has_at_least_three_groups() {
    let mut a = open(read(RECOVERY_VECTOR), RECOVERY_VECTOR, None);
    let r = a.check_recovery().unwrap();
    assert!(r.frames >= 3, "{r:?}");
    assert_eq!((r.shards_damaged, r.frames_unusable), (0, 0));
}

#[test]
fn expected_toml_matches_the_reference_reader() {
    let want = String::from_utf8(read("expected.toml")).unwrap();
    assert!(
        want.replace("\r\n", "\n") == render(),
        "expected.toml is out of date; regenerate with --ignored"
    );
}

#[test]
fn the_malformed_vectors_are_derived_from_zstd_basic() {
    let (truncated, flipped) = malformed();
    assert!(read(TRUNCATED) == truncated);
    assert!(read(HASHFLIP) == flipped);
}

/// CONFORMANCE "malformed-hashflip" and spec section 9 (E1-14d ruling 1):
/// extracting a file of the damaged block fails with the block frame's
/// `HashMismatch { kind: 2 }`, the same error as `verify`.
#[test]
fn hashflip_extraction_is_the_frame_hash_mismatch() {
    let mut a = open(read(HASHFLIP), HASHFLIP, None);
    let t = a.entry_table().unwrap();
    let entries = t
        .table()
        .unwrap()
        .iter()
        .collect::<Result<Vec<_>, _>>()
        .unwrap();
    assert!(!entries.is_empty());
    for e in &entries {
        let mut sink = Vec::new();
        assert!(matches!(
            a.extract(e, &mut sink),
            Err(lpk_format::FormatError::HashMismatch { kind: 2 })
        ));
    }
}

#[test]
#[ignore = "rewrites tests/vectors/expected.toml and the malformed vectors"]
fn regenerate() {
    let (truncated, flipped) = malformed();
    std::fs::write(vectors_dir().join(TRUNCATED), truncated).unwrap();
    std::fs::write(vectors_dir().join(HASHFLIP), flipped).unwrap();
    std::fs::write(vectors_dir().join("expected.toml"), render()).unwrap();
}
