//! The revision 1.1 vector `jpeg-peel.lpk` (in `crates/lpk-format/tests/vectors/`), built by the
//! JPEG peel through the Fast pipeline, and its full-reader expectations
//! (`expected-1.1.toml` beside it). The 1.0 expectations (listing, `info`, the
//! `UnimplementedPrimitive` of `verify`) are in `expected.toml`, written by lpk-format's
//! conformance test. Regenerate with
//! `cargo test -p lpk-core --test jpeg_vector -- --ignored`, then lpk-format's
//! `cargo test -p lpk-format --test conformance -- --ignored`.
#![allow(clippy::unwrap_used)]

use std::fmt::Write as _;
use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::time::{Duration, UNIX_EPOCH};

use lpk_core::{register_full_reader, FastOptions, Pipeline};
use lpk_format::{Archive, EntryKind, Resources};

const VECTOR: &str = "jpeg-peel.lpk";
const EXPECTED: &str = "expected-1.1.toml";

fn vectors() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("lpk-format")
        .join("tests")
        .join("vectors")
}

fn fixture(name: &str) -> Vec<u8> {
    std::fs::read(
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join(name),
    )
    .unwrap()
}

/// `photo.jpg`: the baseline fixture with an APP2 `MPF\0` segment, then the secondary fixture
/// after its EOI with a few bytes before and after it.
fn photo() -> Vec<u8> {
    let base = fixture("baseline.jpg");
    let mut v = base[..2].to_vec();
    v.extend_from_slice(&[0xFF, 0xE2, 0x00, 0x0A]);
    v.extend_from_slice(b"MPF\0\0\0\0\0");
    v.extend_from_slice(&base[2..]);
    v.extend_from_slice(b"gap");
    v.extend_from_slice(&fixture("secondary.jpg"));
    v.extend_from_slice(b"tail bytes");
    v
}

fn set_mtime(p: &Path) {
    let f = std::fs::File::options().write(true).open(p).unwrap();
    f.set_modified(UNIX_EPOCH + Duration::from_nanos(1000))
        .unwrap();
}

/// The vector's bytes: chunk size 4096, archive id 0x5A repeated, mtime 1000 ns.
fn build() -> Vec<u8> {
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("photo.jpg");
    std::fs::write(&p, photo()).unwrap();
    set_mtime(&p);
    let mut pipeline = Pipeline::fast(FastOptions::default());
    pipeline.seal.writer.chunk_size = 4096;
    pipeline.seal.writer.archive_id = [0x5A; 16];
    let mut out = Vec::new();
    let s = pipeline.run(dir.path(), &mut out).unwrap();
    assert_eq!(s.peel.peeled.files, 1);
    out
}

fn tool(args: &[&str]) -> (i32, String) {
    let (mut out, mut err) = (Vec::new(), Vec::new());
    let code = lpk_format::cli::run_with(
        args.iter().copied(),
        &mut out,
        &mut err,
        register_full_reader::<std::fs::File>,
    );
    assert_eq!(String::from_utf8(err).unwrap(), "");
    (code, String::from_utf8(out).unwrap())
}

fn render() -> String {
    let path = vectors().join(VECTOR);
    let mut a = Archive::open(
        Cursor::new(std::fs::read(&path).unwrap()),
        &Resources::default(),
    )
    .unwrap();
    register_full_reader(&mut a);
    let t = a.entry_table().unwrap();
    let entries: Vec<_> = t.table().unwrap().iter().map(|e| e.unwrap()).collect();
    let mut s = String::from(
        "# Expected results of a revision 1.1 reader (docs/spec/CONFORMANCE.md).\n\
         # Generated by lpk-core's full reader; do not edit. `files`: path size BLAKE3-256 of the\n\
         # extracted bytes, in entry-table order; `verify` is the stdout of `verify` (exit code 0).\n",
    );
    writeln!(s, "\n[\"{VECTOR}\"]").unwrap();
    writeln!(s, "files = [").unwrap();
    for e in &entries {
        let mut got = Vec::new();
        if e.kind == EntryKind::File {
            a.extract(e, &mut got).unwrap();
        }
        let line = format!("{} {} {}", e.path, got.len(), blake3::hash(&got).to_hex());
        writeln!(s, "  {line:?},").unwrap();
    }
    writeln!(s, "]").unwrap();
    let (code, out) = tool(&["lpk", "verify", path.to_str().unwrap()]);
    assert_eq!(code, 0);
    writeln!(s, "verify = {out:?}").unwrap();
    s
}

/// The vector is committed as the workspace build writes it (`cargo nextest run --workspace`,
/// what CI runs). `lepton_jpeg` deflates its stream header with `flate2`, whose backend Cargo
/// unifies across the build: in the workspace `lpk-bench` enables the zlib backend, while
/// `lpk-core` built alone gets `miniz_oxide`, and the two write different (equally valid) zlib
/// bytes. The committed vector was written by the workspace build, that is with flate2's zlib
/// backend. A build with the other backend gets a structural check instead of byte identity:
/// the same Merkle root (the chunk table hashes the original bytes), the same record, the same
/// nested block, and the same extracted file. When the environment variable `CI` is set (CI
/// builds the workspace, the backend of the committed vector) a difference fails instead.
#[test]
fn the_vector_regenerates_identically() {
    let committed = std::fs::read(vectors().join(VECTOR)).unwrap();
    let built = build();
    if committed == built {
        return;
    }
    assert!(
        std::env::var_os("CI").is_none(),
        "jpeg-peel.lpk differs from this build's under CI, where byte identity is required"
    );
    eprintln!("jpeg-peel.lpk differs from this build's (flate2 backend?): structural check");
    let open = |b: Vec<u8>| {
        let mut a = Archive::open(Cursor::new(b), &Resources::default()).unwrap();
        register_full_reader(&mut a);
        a
    };
    let (mut a, mut b) = (open(committed.clone()), open(built.clone()));
    assert_eq!(a.index().merkle_root, b.index().merkle_root);
    let rec = |x: &mut Archive<Cursor<Vec<u8>>>| {
        x.records()
            .unwrap()
            .unwrap()
            .table()
            .unwrap()
            .get(0)
            .unwrap()
    };
    assert_eq!(rec(&mut a), rec(&mut b));
    let first = |x: &Archive<Cursor<Vec<u8>>>, bytes: &[u8]| {
        let l = x.index().blocks[0];
        bytes[l.frame_offset as usize..(l.frame_offset + l.frame_len) as usize].to_vec()
    };
    assert!(first(&a, &committed) == first(&b, &built));
    for x in [&mut a, &mut b] {
        x.verify().unwrap();
        let e = x
            .entry_table()
            .unwrap()
            .table()
            .unwrap()
            .iter()
            .next()
            .unwrap()
            .unwrap();
        let mut got = Vec::new();
        x.extract(&e, &mut got).unwrap();
        assert!(got == photo());
    }
}

#[test]
fn the_vector_extracts_to_the_original_and_matches_its_expectations() {
    let want = std::fs::read_to_string(vectors().join(EXPECTED)).unwrap();
    assert_eq!(want.replace("\r\n", "\n"), render());
    let line = format!(
        "photo.jpg {} {}",
        photo().len(),
        blake3::hash(&photo()).to_hex()
    );
    assert!(want.contains(&line), "{want}");
    let a = Archive::open(
        Cursor::new(std::fs::read(vectors().join(VECTOR)).unwrap()),
        &Resources::default(),
    )
    .unwrap();
    assert_eq!(a.header().version.minor, 1);
}

/// The independent 1.0 decoder (`lpk-check`, unchanged) reports `UnimplementedPrimitive` for
/// primitive 7 on the vector.
#[test]
fn lpk_check_reports_unimplemented_primitive_7() {
    let exe = std::env::current_exe().unwrap();
    let dir = exe.parent().unwrap().parent().unwrap();
    let bin = dir.join(format!("lpk-check{}", std::env::consts::EXE_SUFFIX));
    if !bin.exists() {
        let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
        let st = std::process::Command::new(cargo)
            .args(["build", "-p", "lpk-check"])
            .status()
            .unwrap();
        assert!(st.success());
    }
    let out = std::process::Command::new(&bin)
        .arg("verify")
        .arg(vectors().join(VECTOR))
        .output()
        .unwrap();
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(!out.status.success(), "{text}");
    assert!(text.contains("0x0007"), "{text}");
    // The tool prints the message only; the class comes from the same decoder as a library.
    let data = std::fs::read(vectors().join(VECTOR)).unwrap();
    let e = lpk_check::archive::Archive::open(data, lpk_check::archive::Options::default())
        .unwrap()
        .verify()
        .unwrap_err();
    assert_eq!(e.class, "UnimplementedPrimitive");
    assert!(e.to_string().contains("0x0007"), "{e}");
}

#[test]
#[ignore = "rewrites jpeg-peel.lpk and expected-1.1.toml in crates/lpk-format/tests/vectors"]
fn regenerate() {
    std::fs::write(vectors().join(VECTOR), build()).unwrap();
    std::fs::write(vectors().join(EXPECTED), render()).unwrap();
}
