//! The Markdown of the report. Every number in sections 2 to 6 is printed through
//! [`Traced::show`], so it carries its source bracket.

use std::collections::BTreeSet;

use super::model::{
    blend, class_bytes, est_kind, gates, settings, unclean_reasons, verdict_line, Baseline,
    EstKind, Inputs, Model, RowState, RULED, RULES,
};
use super::traced::{brackets, Traced};
use crate::probe::{md_table, render_file};
use crate::run::result::AvProduct;

fn pct1(v: f64) -> String {
    format!("{v:.1}%")
}
fn pct_of_class(v: f64) -> String {
    format!("{v:.1}% of class")
}
fn bytes_s(v: f64) -> String {
    format!("{v:.0} bytes")
}
fn mbps_s(v: f64) -> String {
    format!("{v:.1}")
}
fn mib_s(v: f64) -> String {
    format!("{v:.1}")
}
fn count_s(v: f64) -> String {
    format!("{v:.0}")
}

/// The date of the baseline run: the first ten characters of its directory name.
pub fn baseline_date(b: &Baseline) -> String {
    b.dir.chars().take(10).collect()
}

fn av_list(v: &[AvProduct]) -> String {
    if v.is_empty() {
        return "no product listed".to_string();
    }
    v.iter()
        .map(|p| {
            format!(
                "{} (scanner {}, state {})",
                p.name, p.scanner, p.product_state
            )
        })
        .collect::<Vec<_>>()
        .join("; ")
}

const PROBE_WHAT: [(&str, &str); 6] = [
    (
        "jpeg",
        "Lepton recompression of every JPEG of the photo classes, verified bit for bit, with the failures by cause",
    ),
    (
        "deflate",
        "Deflate streams inside PDF, Office, PNG, ZIP and similar containers: reconstruction by preflate-rs and the net gain after recompressing the plain data",
    ),
    (
        "dedup",
        "content-defined chunking and BLAKE3 duplicate detection, and zstd patch sizes between backup versions",
    ),
    (
        "text",
        "xz, zstd and, where installed, bsc and kanzi on the text, log and small-file classes",
    ),
    (
        "weights",
        "byte-plane and rotated-plane splitting of safetensors tensors before zstd",
    ),
    (
        "entropy-gate",
        "how well cheap block gates predict incompressible data, the gates' cost and the raw read speed per class",
    ),
];

/// Lines starting with `#` move down three levels.
fn demote(md: &str) -> String {
    md.lines()
        .map(|l| {
            if l.starts_with('#') {
                format!("###{l}")
            } else {
                l.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn render(inputs: &Inputs) -> String {
    let b = &inputs.baseline;
    let model = Model::build(inputs);
    let mut s = String::new();
    let unclean = unclean_reasons(inputs);
    let origin = if inputs.outside.is_empty() {
        "committed result files"
    } else {
        "result files, not all of them under bench/results"
    };
    s.push_str(&format!(
        "# {}LitePack Phase 0 report, baseline run of {}\n\n\
         Generated by `lpk-bench report` from {origin}. Every number in sections 2 \
         to 6 is followed by the index of its source in brackets (list in section 7); a number \
         derived from several files carries all of them. Estimates are labelled as estimates and \
         never share a column with measurements. The verdict is recorded by a person in D-08, not \
         by this command.\n\n",
        if unclean.is_empty() {
            ""
        } else {
            "UNCLEAN INPUTS: "
        },
        baseline_date(b)
    ));
    header(&mut s, inputs, &model);
    baseline_per_class(&mut s, &model, inputs);
    baseline_blended(&mut s, &model, inputs);
    probes(&mut s, inputs);
    estimates(&mut s, &model, inputs);
    gate_section(&mut s, &model, inputs);
    sources(&mut s, inputs);
    caveats(&mut s, &model, inputs);
    s
}

fn header(s: &mut String, inputs: &Inputs, m: &Model) {
    let b = &inputs.baseline;
    s.push_str("## 1. Header\n\n");
    if let Some((r, src)) = b.results.first() {
        let cb = class_bytes(&m.rows);
        let files: Vec<Traced> = {
            let mut seen = BTreeSet::new();
            m.rows
                .iter()
                .filter(|r| seen.insert(r.class.clone()))
                .map(|r| Traced {
                    value: r.class_files as f64,
                    sources: r.class_bytes.sources.clone(),
                })
                .collect()
        };
        let bytes: Vec<&Traced> = cb.values().collect();
        let tot_files = Traced::sum(&files);
        let tot_bytes = Traced::sum(bytes);
        s.push_str(&format!(
            "- corpus: profile `{}`, manifest BLAKE3 `{}`{}, {} files, {} bytes, {} classes ({})\n",
            r.corpus.profile,
            r.corpus.manifest_blake3,
            if r.private { ", private" } else { "" },
            tot_files.map_or("n/a".to_string(), |t| t.show(count_s)),
            tot_bytes.map_or("n/a".to_string(), |t| t.show(count_s)),
            cb.len(),
            brackets(&BTreeSet::from([*src]))
        ));
    }
    let h = &b.host;
    s.push_str(&format!(
        "- host `{}`: {}, {} logical cores, {} bytes RAM, {} {} {}\n",
        h.host,
        h.cpu_model,
        h.logical_cores,
        h.ram_bytes,
        h.os,
        h.os_version,
        brackets(&BTreeSet::from([b.host_src]))
    ));
    s.push_str(&format!(
        "- baseline build: lpk-bench {} at commit `{}`, {}, run dated {} {}\n",
        h.lpk_bench_version,
        h.git_commit,
        h.rustc_version,
        baseline_date(b),
        brackets(&BTreeSet::from([b.host_src]))
    ));
    for p in inputs.probes.present() {
        s.push_str(&format!(
            "- probe `{}` build: `{}`{}, taken {} on `{}` [{}]\n",
            p.name,
            p.build,
            if p.release {
                ""
            } else {
                " (not a release build)"
            },
            p.date,
            p.host,
            p.src
        ));
    }
    let unclean = unclean_reasons(inputs);
    if !unclean.is_empty() {
        s.push_str(&format!(
            "- **UNCLEAN INPUTS ALLOWED** (`--allow-unclean`): {}\n",
            unclean.join("; ")
        ));
    }
    let tools: Vec<String> = b
        .tools
        .tools
        .iter()
        .map(|t| match (&t.status[..], &t.version) {
            ("found", Some(v)) => format!("{} {}", t.name, v),
            _ => format!("{} (skipped)", t.name),
        })
        .collect();
    s.push_str(&format!(
        "- tools: {} {}\n",
        tools.join(", "),
        brackets(&BTreeSet::from([b.tools_src]))
    ));
    let mut libs: Vec<String> = Vec::new();
    for p in inputs.probes.present() {
        for (k, v) in &p.libraries {
            let l = format!("{k} {v} [{}]", p.src);
            if !libs.contains(&l) {
                libs.push(l);
            }
        }
    }
    if !libs.is_empty() {
        s.push_str(&format!(
            "- libraries (from the probe files): {}\n",
            libs.join(", ")
        ));
    }
    let rb = brackets(&BTreeSet::from([b.run_src]));
    s.push_str(&format!(
        "- antivirus at the start of the baseline run: {} (Windows Defender real-time: {}) {}; at \
         the end: {} {}; changed during the run: {}\n",
        av_list(&h.antivirus),
        h.defender_realtime,
        brackets(&BTreeSet::from([b.host_src])),
        av_list(&b.run.antivirus_end),
        rb,
        if b.run.antivirus_changed { "yes" } else { "no" }
    ));
    s.push_str(&format!(
        "- catalogue BLAKE3 `{}`; run settings: {} repeats requested, long-run limit {} s, \
         settle pause {} ms per 1000 files, {} threads {}\n\n",
        b.run.catalogue_blake3,
        b.run.repeats_requested,
        b.run.long_run_s,
        b.run.settle_ms_per_1000_files,
        b.run.threads,
        rb
    ));
}

fn baseline_per_class(s: &mut String, m: &Model, inputs: &Inputs) {
    s.push_str("## 2. Baseline, per class\n\n");
    s.push_str(
        "Archive size is a percentage of the class's bytes. MB/s = class bytes / median wall \
         seconds (MB = 10^6 bytes). Peak memory is the larger of the compress and extract \
         medians (peak working set on Windows, maximum RSS on Linux), in MiB. A tool/setting \
         marked `*` rests on one measurement.\n\n",
    );
    for class in &inputs.baseline.run.classes {
        let rows: Vec<_> = m.rows.iter().filter(|r| &r.class == class).collect();
        let Some(first) = rows.first() else { continue };
        s.push_str(&format!(
            "### {class}: {} files, {}\n\n",
            Traced {
                value: first.class_files as f64,
                sources: first.class_bytes.sources.clone()
            }
            .show(count_s),
            first.class_bytes.show(|v| format!("{v:.0} bytes"))
        ));
        let table: Vec<Vec<String>> = rows
            .iter()
            .map(|r| {
                let dash = || "-".to_string();
                match &r.state {
                    RowState::Measured(x) => vec![
                        format!(
                            "{}{}",
                            r.label(),
                            if x.single.is_some() { " *" } else { "" }
                        ),
                        x.size_pct.show(pct1),
                        x.compress_mbps.show(mbps_s),
                        x.extract_mbps.show(mbps_s),
                        x.rss_mib.show(mib_s),
                        x.repeats.show(count_s),
                    ],
                    RowState::Failed { step, reason, src } => vec![
                        r.label(),
                        format!(
                            "FAILED ({step}): {reason} {}",
                            brackets(&BTreeSet::from([*src]))
                        ),
                        dash(),
                        dash(),
                        dash(),
                        dash(),
                    ],
                    RowState::Skipped { reason, src } => vec![
                        r.label(),
                        format!("skipped: {reason} {}", brackets(&BTreeSet::from([*src]))),
                        dash(),
                        dash(),
                        dash(),
                        dash(),
                    ],
                }
            })
            .collect();
        s.push_str(&md_table(
            &[
                "tool/setting",
                "archive size (% of class bytes)",
                "compress MB/s",
                "extract MB/s",
                "peak memory (MiB)",
                "repeats used",
            ],
            &table,
        ));
        s.push('\n');
    }
}

fn baseline_blended(s: &mut String, m: &Model, inputs: &Inputs) {
    s.push_str("## 3. Baseline, blended\n\n");
    s.push_str(&format!(
        "The disk mixes come from `{}` [{}], printed here in full:\n\n```toml\n{}{}```\n\n",
        inputs
            .sources
            .get(inputs.mixes_src - 1)
            .map_or("", String::as_str),
        inputs.mixes_src,
        inputs.mixes_text,
        if inputs.mixes_text.ends_with('\n') {
            ""
        } else {
            "\n"
        }
    ));
    s.push_str(
        "Size: the weighted sum of the per-class size ratios. Speed: the bytes-weighted harmonic \
         mean of the per-class speeds. A tool/setting without a measured result for every class \
         of the mix shows `n/a`.\n\n",
    );
    let cb = class_bytes(&m.rows);
    let keys = settings(&m.rows);
    for mix in &inputs.mixes.mix {
        let weights: Vec<String> = mix
            .weights
            .iter()
            .map(|(c, w)| format!("{c} {w}"))
            .collect();
        s.push_str(&format!(
            "### Mix `{}`\n\nShares of bytes, in percent [{}]: {}.\n\n",
            mix.name,
            inputs.mixes_src,
            weights.join(", ")
        ));
        let missing = super::model::missing_classes(mix, &cb);
        if !missing.is_empty() {
            s.push_str(&format!(
                "n/a: the corpus has no class {}.\n\n",
                missing.join(", ")
            ));
            continue;
        }
        let rows: Vec<Vec<String>> = keys
            .iter()
            .map(
                |(t, st)| match blend(&m.rows, (t, st), mix, inputs.mixes_src) {
                    Ok(bl) => vec![
                        format!("{t}/{st}{}", if bl.single { " *" } else { "" }),
                        bl.size_pct.show(pct1),
                        bl.compress_mbps.show(mbps_s),
                        bl.extract_mbps.show(mbps_s),
                    ],
                    Err(why) => vec![
                        format!("{t}/{st}"),
                        format!("n/a: {why}"),
                        "-".into(),
                        "-".into(),
                    ],
                },
            )
            .collect();
        s.push_str(&md_table(
            &[
                "tool/setting",
                "blended size (% of mix bytes)",
                "blended compress MB/s",
                "blended extract MB/s",
            ],
            &rows,
        ));
        s.push('\n');
    }
}

fn probes(s: &mut String, inputs: &Inputs) {
    s.push_str("## 4. Probes\n\n");
    s.push_str(
        "Each table below is rendered from the probe's JSON by the same function `lpk-bench probe` \
         uses; the figures inside carry the one source named in the line above them.\n\n",
    );
    let present = inputs.probes.present();
    for (name, what) in PROBE_WHAT {
        match present.iter().find(|p| p.name == name) {
            None => s.push_str(&format!(
                "### Probe `{name}`\n\nNot available: no `probe-{name}.json` was given.\n\n"
            )),
            Some(p) => {
                s.push_str(&format!(
                    "### Probe `{name}`\n\nMeasured: {what}. Build `{}`{} [{}].\n\n",
                    p.build,
                    if p.release {
                        ""
                    } else {
                        " (not a release build)"
                    },
                    p.src
                ));
                match render_file(name, &p.json) {
                    Ok(md) => {
                        s.push_str(&demote(&md));
                        s.push('\n');
                    }
                    Err(e) => s.push_str(&format!("The table could not be rendered: {e}\n\n")),
                }
            }
        }
    }
}

fn estimates(s: &mut String, m: &Model, inputs: &Inputs) {
    s.push_str("## 5. Estimates\n\n");
    s.push_str(
        "The estimate column is the figure derived from the probes by the rule for the class; it \
         combines component measurements and assumes nothing about the container, deduplication \
         across classes or the Fold stage. Measured and estimated figures are in separate \
         columns. In the per-class table the best measured incumbent is the smallest archive \
         among all measured tools and settings of that class (a `*` marks a row that rests on one \
         measurement). For the disk mixes and for gate G1 the best measured incumbent is the best \
         single tool x setting over the combined bytes, because D-07 names one competitor; the \
         sum of the per-class bests (which no single tool achieves) is printed as a stricter \
         second figure. For a class with no rule the estimate cell reads `= best incumbent, no \
         rule`, for video and encrypted-random `stored, no rule`: no gain is claimed there.\n\n",
    );
    let rows: Vec<Vec<String>> = m
        .classes
        .iter()
        .map(|c| {
            let na = || "not available".to_string();
            let est = match &c.est {
                Ok(e) => (
                    match est_kind(&c.class) {
                        EstKind::Probe => e.bytes.show(bytes_s),
                        EstKind::NoRule => format!("= best incumbent, no rule {}", e.bytes.tag()),
                        EstKind::Stored => format!("stored, no rule {}", e.bytes.tag()),
                    },
                    (&e.bytes / &c.class_bytes)
                        .map(|x| x * 100.0)
                        .show(pct_of_class),
                ),
                Err(_) => (na(), "-".into()),
            };
            vec![
                c.class.clone(),
                c.class_bytes.show(bytes_s),
                c.best.as_ref().map_or("-".into(), |b| b.name.clone()),
                c.best.as_ref().map_or(na(), |b| b.bytes.show(bytes_s)),
                c.best.as_ref().map_or("-".into(), |b| {
                    (&b.bytes / &c.class_bytes)
                        .map(|x| x * 100.0)
                        .show(pct_of_class)
                }),
                c.ultra.as_ref().map_or(na(), |u| u.show(bytes_s)),
                c.ultra.as_ref().map_or("-".into(), |u| {
                    (u / &c.class_bytes).map(|x| x * 100.0).show(pct_of_class)
                }),
                est.0,
                est.1,
            ]
        })
        .collect();
    s.push_str(&md_table(
        &[
            "class",
            "class bytes",
            "best measured incumbent",
            "best incumbent size",
            "best incumbent, % of class",
            "7-Zip Ultra size",
            "7-Zip Ultra, % of class",
            "LitePack Balanced, estimate",
            "estimate, % of class",
        ],
        &rows,
    ));
    s.push_str("\nRules, one per class group:\n\n");
    for (classes, rule) in RULES {
        s.push_str(&format!("- {classes}: {rule}.\n"));
    }
    s.push_str("\nWhat each class's estimate used:\n\n");
    for c in &m.classes {
        match &c.est {
            Ok(e) => s.push_str(&format!("- {}: {}.\n", c.class, e.basis)),
            Err(why) => s.push_str(&format!("- {}: not available: {why}.\n", c.class)),
        }
    }
    s.push_str(
        "\nPer disk mix (ratios of the mix's bytes: the weighted sum of the class ratios above):\n\n",
    );
    let rows: Vec<Vec<String>> = m
        .mixes
        .iter()
        .map(|x| {
            let f = |r: &Result<Traced, String>| match r {
                Ok(t) => t.show(pct1),
                Err(_) => "n/a".to_string(),
            };
            vec![
                x.name.clone(),
                x.best.as_ref().map_or("-".into(), |b| b.name.clone()),
                x.best
                    .as_ref()
                    .map_or("n/a".to_string(), |b| b.bytes.show(pct1)),
                f(&x.best_per_class),
                f(&x.ultra),
                f(&x.est),
            ]
        })
        .collect();
    s.push_str(&md_table(
        &[
            "mix",
            "best measured incumbent (single tool x setting)",
            "best single tool, % of mix bytes",
            "stricter: per-class bests",
            "7-Zip Ultra",
            "LitePack Balanced, estimate",
        ],
        &rows,
    ));
    s.push('\n');
    for x in &m.mixes {
        for (what, r) in [
            ("best single tool", x.best.as_ref().map(|_| ())),
            ("per-class bests", x.best_per_class.as_ref().map(|_| ())),
            ("7-Zip Ultra", x.ultra.as_ref().map(|_| ())),
            ("estimate", x.est.as_ref().map(|_| ())),
        ] {
            if let Err(why) = r {
                s.push_str(&format!("- mix {}, {what}: n/a: {why}.\n", x.name));
            }
        }
    }
    s.push('\n');
    let _ = inputs;
}

fn gate_section(s: &mut String, m: &Model, inputs: &Inputs) {
    s.push_str("## 6. Gates (D-07)\n\n");
    let g = gates(m, inputs);
    let rows: Vec<Vec<String>> = g
        .iter()
        .map(|r| vec![r.title.clone(), r.numbers.join("<br>"), r.verdict.word()])
        .collect();
    s.push_str(&md_table(&["gate", "numbers", "result"], &rows));
    let unclean = !unclean_reasons(inputs).is_empty();
    s.push_str(&format!(
        "\n**{}{}**\n\n",
        if unclean { "UNCLEAN INPUTS: " } else { "" },
        verdict_line(&g)
    ));
    for r in &g {
        for n in &r.notes {
            s.push_str(&format!("- {n}\n"));
        }
    }
    s.push_str(
        "\nPASS needs the stated numbers; a gate whose data is missing is `not evaluable` and is \
         never a PASS. A `*` after a tool name marks a row that rests on one measurement. G1 uses \
         the fallback wording of D-07 with the best single tool x setting over the combined \
         bytes; the stricter sum of per-class bests is printed beneath it. G3 uses the baseline \
         `store` tool as the measured proxy for storing a file. The baseline's reads are \
         cache-warm (inputs are re-read before each tool), its writes are flushed outside the \
         timed interval and its time includes process start; the probe's raw read is uncached and \
         read-only, so the two rates are not measured the same way. G4 uses zstd level 3 as the \
         proxy for the Fast tier. The verdict is recorded by a person in D-08.\n\n",
    );
}

fn sources(s: &mut String, inputs: &Inputs) {
    s.push_str("## 7. Sources\n\n");
    for (i, p) in inputs.sources.iter().enumerate() {
        s.push_str(&format!("{}. `{p}`\n", i + 1));
    }
    s.push('\n');
}

fn caveats(s: &mut String, m: &Model, inputs: &Inputs) {
    let b = &inputs.baseline;
    s.push_str("## 8. Caveats\n\n");
    let skipped: Vec<String> = b
        .tools
        .tools
        .iter()
        .filter(|t| t.status != "found")
        .map(|t| format!("{} ({})", t.name, t.reason.as_deref().unwrap_or("skipped")))
        .collect();
    s.push_str(&format!(
        "- tools skipped: {}\n",
        if skipped.is_empty() {
            "none".to_string()
        } else {
            skipped.join(", ")
        }
    ));
    let mut failed: Vec<String> = Vec::new();
    let mut single: Vec<String> = Vec::new();
    for r in &m.rows {
        match &r.state {
            RowState::Failed { .. } => failed.push(format!("{} on {}", r.label(), r.class)),
            RowState::Measured(x) => {
                if let Some(why) = &x.single {
                    single.push(format!("{} on {} ({why})", r.label(), r.class));
                }
            }
            RowState::Skipped { .. } => {}
        }
    }
    s.push_str(&format!(
        "- combinations that failed: {}\n",
        if failed.is_empty() {
            "none".to_string()
        } else {
            failed.join(", ")
        }
    ));
    s.push_str(&format!(
        "- rows resting on one measurement (D-20 item 3): {}\n",
        if single.is_empty() {
            "none".to_string()
        } else {
            single.join("; ")
        }
    ));
    let missing = inputs.probes.missing();
    s.push_str(&format!(
        "- probes not available: {}\n",
        if missing.is_empty() {
            "none".to_string()
        } else {
            missing.join(", ")
        }
    ));
    let unruled: Vec<&str> = b
        .run
        .classes
        .iter()
        .map(String::as_str)
        .filter(|c| !RULED.contains(c))
        .collect();
    s.push_str(&format!(
        "- classes without an estimate rule (the best measured incumbent is used, no gain claimed): {}\n",
        if unruled.is_empty() { "none".to_string() } else { unruled.join(", ") }
    ));
    s.push_str(&format!(
        "- antivirus: {}; scanner state at the start of the baseline run: {}; at the end: {}\n",
        if b.run.antivirus_changed {
            "the scanner state changed during the run"
        } else {
            "the scanner state did not change during the run"
        },
        av_list(&b.host.antivirus),
        av_list(&b.run.antivirus_end)
    ));
    let unclean = unclean_reasons(inputs);
    s.push_str(&format!(
        "- unclean inputs (dirty, unknown or unoptimised builds, no settle pause, directories \
         outside bench/results): {}\n",
        if unclean.is_empty() {
            "none".to_string()
        } else {
            unclean.join("; ")
        }
    ));
    s.push_str(
        "- the baseline's build profile is not recorded in its host file, so whether it was a \
         release build cannot be checked from the result files\n",
    );
    s.push_str(
        "- the `small-files` text estimate compresses a tar stream of the class, so tar header \
         bytes are included in it; the baseline sizes are of each tool's own archive\n",
    );
    s.push_str(
        "- probe text timing: `in-process` rows time a library call on a stream in memory, \
         `process-wall` rows time a whole external program including start-up and file I/O; the two \
         bases are not comparable, and the estimates here use sizes only\n",
    );
    s.push_str(
        "- estimates are derived from component measurements on one corpus; they are not archives \
         that were written and read back\n",
    );
}
